# Generated by Django 4.2.6 on 2023-10-29 06:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("objects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("email", models.EmailField(max_length=254)),
                (
                    "chain_object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contact", to="objects.chainobject"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("country", models.CharField(max_length=127)),
                ("city", models.CharField(max_length=127)),
                ("street", models.CharField(max_length=127)),
                ("building", models.CharField(max_length=127)),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="address", to="contacts.contact"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
