# Generated by Django 4.2.6 on 2023-11-01 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(max_length=127)),
                ("city", models.CharField(max_length=127)),
                ("street", models.CharField(max_length=127)),
                ("building", models.CharField(max_length=127)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
